billboard/billboard/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('board/', include('board.urls')),
]

billboard/board/urls.py
from django.urls import path, re_path
from .views import *


urlpatterns = [
    path('', PostsList.as_view(), name='post_list'),
    path('<int:pk>', PostView.as_view(), name='post_view'),
    path('search/', PostSearch.as_view(), name='post_search'),
    path('search/<int:pk>', PostView.as_view(), name='post_view_from_search_page'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('my_posts/', PersonalPostsList.as_view(), name='my_posts_list'),
    path('my_posts/<int:pk>', PostView.as_view(), name='post_view_from_my_posts'),
    path('repy_on_comment/<int:pk>', CommentReply.as_view(), name='reply_comment'),
    path("email-confirmation/<int:pk>", MyEmailAddressConfirmation.as_view(), name="my_account_confirm_email"),


]

billboard/board/models.py
from ckeditor.fields import RichTextField

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    CATEGORY_LIST = [
        ("tank", "Танки"),
        ('heal', "Хилы"),
        ("dd", "ДД"),
        ("buyers", "Торговцы"),
        ("gildemaster", "Гилдмастеры"),
        ("quest", "Квестгиверы"),
        ("smith", "Кузнецы"),
        ("tanner", "Кожевники"),
        ("potion", "Зельевары"),
        ("spellmaster", "Мастера заклинаний"),

    ]

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    body = RichTextField(blank=True, null=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=20, choices=CATEGORY_LIST)

    def __str__(self):
        return (f'{self.title}')

    def get_absolute_url(self):
        return reverse('post_view', args=[str(self.id)])

class Replies(models.Model):
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date_creation = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)


class RandomNumber(models.Model): # модель для сохранения сгенерированного случайного числа при регистрации
    number = models.IntegerField()
    related_user = models.ForeignKey(User, on_delete=models.CASCADE)

billboard/templates/myposts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Заголовок вкладки
{% endblock title  %}


{% block content %}
    <h1 align="left" style="color: #333333"><b>Мои объявления</b></h1>
    <hr>
        <div align="left" class="form-group" style=" width: 600px">
            <div class="list-group"  style="border-radius:10px;display: flex">
                <a class="list-group-item list-group-item list-group-item-warning" style="height:45px; text-decoration: none; color: #000000">
                    <div style="width:88%; float:left; font-weight:bold">
                        <p>Объявления (всего {% if posts_amount%} {{posts_amount}} {%endif%})</p>
                    </div>
                    <div style="width:12%; float:right; font-weight:bold">
                        <p>Отклики</p>
                    </div>
                </a>
                <!-- Контент -->
                {% if MyPosts %}
                    {% for post in MyPosts %}
                        <a href="{% url 'post_view_from_my_posts' post.id %}" class="list-group-item list-group-item-action list-group-item-light">
                            <div style="width:90%;float: left;">

                                {{post.date_creation|month_translation}} {{post.date_creation|date:"H:i"}}
                                |
                                {{post.title}}
                            </div>
                            <div style="width:10%; float:right">
                                <span class="btn btn-outline-warning" style="width:40px; font-size:9px; color:black;">
                                    {{ post|replies_amount }}
                                </span>
                            </div>
                        </a>
                    {%endfor%}
                {% else %}
                    <a href="{% url 'post_create' %}" class="list-group-item list-group-item-action list-group-item-light">
                        <div style="width:80%;float: left;">
                            У Вас нет объявлений. Выложите своё первое объявление
                        </div>
                        <div style="width:20%; float:right">
                            <span class="btn btn-outline-warning" style="width:100px; font-size:10px; color:black; ">
                                СОЗДАТЬ!
                            </span>
                        </div>
                    </a>
                {% endif %}
            </div>
        </div>

        <hr>

{% endblock content %}

billboard/templates/one_post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Объявление:
{{ OnePost.title }}
{% endblock title %}


{% block content %}

<h1 style="font-size:50px; border-radius:10px; margin-top:20px; background: linear-gradient(245deg,#F00B51,#73005C); padding:20px; color:black"><b>{{ OnePost.title }}</b></h1>
<hr>
<br>
<div align="left" style="border-radius: 10px; background: linear-gradient(45deg,#CCCCCC,#FFFFFF); padding: 20px; color:#black; margin-bottom: 40px">
    <p align="center" style="font-size:30px; margin: -15px">{% if OnePost.author.username == 'admin' %}Администрация сайта {%else%} {{OnePost.author}} {%endif%}</p>
    <hr>
    <p>{{ OnePost.body|safe }}</p>
    <hr>
    <table style="width: 100%;">
        <tr>

            <td align="center">
                {% if OnePost.author.username == user.username %}
                {% if perms.board.change_post %}
                    <a href="{% url 'post_update' OnePost.id%}" class="btn btn-warning" >Редактировать</a>
                {% endif %}
                {% endif %}
            </td>

            <td>
                <p align="center" style="font-size:12px; color: #696969">Опубликовано {{OnePost.date_creation|month_translation}} {{OnePost.date_creation|date:"H:i"}} в категорию "{{ OnePost.category|readable_category }}"</p>
            </td>
            <td align="center">
                {% if OnePost.author.username == user.username %}
                {% if perms.board.delete_post %}
                    <a href="{% url 'post_delete' OnePost.id%}" class="btn btn-danger">Удалить</a>
                {% endif %}
                {% endif %}
            </td>
        </tr>
    </table>
    {% if user.username %} <!-- Проверка авторизации пользователя -->
        <hr>
        {% if OnePost.author.username == user.username %} <!-- Проверка соответствия автора поста с текущим пользователем -->
            <p align="left" style="font-size:20px;">Отклики к объявлению:</p>
            <div style="margin-left:5px; width: 680px;padding: 20px; ">
                {% if comments %}
                    {% for comment in comments %}
                        <div class="card border-secondary mb-3" style="max-width: 600px;">
                            <div class="card-header bg-transparent border-secondary" style="{% if comment.author__username == 'admin'%} background: linear-gradient(245deg,#00FFED,#0088BA) {% endif %}">

                                {{comment.date_creation|month_translation}} {{comment.date_creation|date:"H:i"}}
                                |
                                {% if comment.status %}
                                Вы ответили на отклик &#9989;
                                {% else %}
                                Ждёт ответа &#8987; -
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="comment_id" value="{{ comment.id }}" />
                                    <button name="action" value="reply_comment" style="text-align:right; font-size: 12px" class="btn btn-success">Ответить через вью</button>
                                </form>
                                <form method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="comment_id" value="{{ comment.id }}" />
                                    <button name="action" value="delete_comment" style="text-align:right; font-size: 12px" class="btn btn-danger">Удалить</button>
                                </form>
                                {%endif%}

                            </div>
                            <div class="card-body text-secondary">
                                <h5 class="card-title" style="color:black; font-size: 17px">{{comment.author__username}} откликнулся:</h5>
                                <p class="card-text" style="font-size:13px; color: #555555">{{comment.text}}</p>
                            </div>
                        </div>
                    {%endfor%}
                {% else %}
                <h4>На Ваше объявление пока никто не откликнулся.</h4>
                {% endif %}
            </div>
            <br>
            <hr>
        {% else %}
        <br>

            {% if existing_comment %} <!-- Вывод формы отправки отклика либо вывод сообщения, что отклик уже отправлен -->
                {% if reply_is_replied_on_email %}
                    <div align="center" style="font-size: 20px; font-weight: bold; box-shadow: 0 0 10px 1px #330000; border-radius:20px; width: 300px; margin-left:20px; padding: 15px; background: linear-gradient(245deg,#92F1D5,#ABF6BD)">
                    {{ reply_is_replied_on_email }}
                    </div>
                {% else %}
                <div align="center" style="font-size: 20px; font-weight: bold; box-shadow: 0 0 10px 1px #330000; border-radius:20px; width: 300px; margin-left:20px; padding: 15px; background: linear-gradient(245deg,#FF9482,#7D77FF)">
                    Отклик отправлен
                </div>
                {% endif %}
            {% else %}

            <br>
            <div style="box-shadow: 0 0 10px 1px #330000; border-radius:20px; width: 800px; margin-left:20px; padding: 15px; background: linear-gradient(245deg,#FF9482,#7D77FF)">
                <form action="" method="post" style="width: 700px">
                    <style>
                        label {font-weight:bold}
                    </style>
                    {% csrf_token %}
                    {{ comment_form }}
                    <br>
                    <input type="submit" class="btn btn-secondary" value="Отправить" style="background: linear-gradient(245deg,#F00B51,#73005C); color: white; font-size: 20px; font-weight: bold"/>
                </form>
            </div>
            <br>
            {% endif %}
        {% endif %}
    {% endif %}
    {% if 'search' in request.path %}
    <p align="center"><a href="{% url 'post_search' %}" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 Назад к поиску</a></p>
    {% elif 'my_posts' in request.path %}
    <p align="center"><a href="{% url 'my_posts_list' %}" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 Вернуться к своим объявлениям</a></p>
    {% else %}
    <p align="center"><a href="{% url 'post_list' %}" class="btn btn-secondary" style="margin-top:10px; align:center">&#8592 На главную</a></p>
    {%endif%}
</div>



{% endblock content %}

billboard/templates/post_create.html
{% extends 'flatpages/default.html' %}


{% block title %}
Создание объявления
{% endblock title  %}

{% block content %}


<h1 align="left" style="color: #333333"><b>Новое объявление</b></h1>
<hr>
<div align="left" style="margin-top:15px; margin-bottom: 15px">
    <a href="{% url 'post_list' %}" class="btn btn-danger">&#8592 Отменить и вернуться на главную</a>
</div>
<hr>
<div class="form-group" style="margin-bottom: 25px">
    <form action="" method="post" style="width: 700px">
        <style>
            label {font-weight: bold}
        </style>
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <hr>
        <input type="submit" value="Опубликовать" class="btn btn-secondary" align="center" style="background: linear-gradient(245deg,#F00B51,#73005C); color: white; font-size: 20px; font-weight: bold"/>

    </form>
<hr>
</div>

{% endblock content %}

billboard/templates/post_delete.html
{% extends 'flatpages/default.html' %}


{% block title %}
Удаление объявления
{% endblock title  %}

{% block content %}


<h1 align="left" style="color: #333333"><b>Удаление объявления</b></h1>
<hr>
<div align="left" style="margin-top:15px; margin-bottom: 15px">

</div>
<div align="center" class="form-group" style="margin-bottom: 25px">
    <form action="" method="post" style="width: 700px">
        <h2 align="center" style="color: #333333"><b>Вы уверены, что хотите безвозвратно удалить с сайта объявление</b> <br><br><i style="color: #660000">- {{ object.title }} -</i> </h2>
        {% csrf_token %}
        <br>
        <br>
        <a href="{% url 'post_view' object.id%}" class="btn btn-success" style="color: white; font-size: 20px; font-weight: bold">&#8592 Отменить удаление и вернуться к посту</a>
        <br><br>
        <input type="submit" value="Удалить объявление" class="btn btn-danger" align="center" style="color: white; font-size: 20px; font-weight: bold"/>
        <br><br>
    </form>
<hr>
</div>

{% endblock content %}

billboard/templates/post_edit.html
{% extends 'flatpages/default.html' %}


{% block title %}
Редактирование объявления
{% endblock title  %}

{% block content %}


<h1 align="left" style="color: #333333"><b>Редактирование объявления</b></h1>
<hr>
<div align="left" style="margin-top:15px; margin-bottom: 15px">
    <a href="{% url 'post_view' object.id %}" class="btn btn-danger">&#8592 Отменить изменения и вернуться к посту</a>
</div>
<hr>
<div class="form-group" style="margin-bottom: 25px">
    <form action="" method="post" style="width: 700px">
        <style>
            label {font-weight: bold}
        </style>
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <hr>
        <input type="submit" value="Сохранить изменения" class="btn btn-secondary" align="center" style="background: linear-gradient(245deg,#F00B51,#73005C); color: white; font-size: 20px; font-weight: bold"/>

    </form>
<hr>
</div>

{% endblock content %}

billboard/templates/post_search.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}
{% load custom_filters %}

{% block title %}
Поиск по объявлениям
{% endblock title %}


{% block content %}
    <h1 align="left" style="color: #333333"><b>Поиск объявлений</b></h1>
    <hr>
<!--Форма поиска в виде таблицы-->
    <form action="" method="get" >
        <table style="width:400px">
            {{ filterset.form.non_field_errors }}
            <tr>
                <td>
                    {{ filterset.form.title.errors }}
                    <label for="{{ filterset.form.title.id_for_label}}"><b>Заголовок</b></label>
                </td>
                <td>
                    <input
                        id="{{ filterset.form.title.id }}"
                        name="{{ filterset.form.title.name }}"
                        value="{% if not filterset.form.title.value %}{% else %}{{ filterset.form.title.value }}{% endif %}"
                        class="form-control"
                        placeholder="Введите заголовок или его часть">
                </td>
            </tr>
            <tr>
                <td>
                    {{ filterset.form.body.errors }}
                    <label for="{{ filterset.form.body.id_for_label }}"><b>Содержание</b></label>
                </td>
                <td>
                    <input
                        id="{{ filterset.form.body.id }}"
                        name="{{ filterset.form.body.name }}"
                        value="{% if not filterset.form.body.value %}{% else %}{{ filterset.form.body.value }}{% endif %}"
                        class="form-control"
                        placeholder="Введите ключевые слова">
                </td>
            </tr>
            <tr>
                <td>
                    {{ filterset.form.category.errors }}
                    <label for="id_category"><b>Категория</b></label>
                </td>
                <td>
                    <select name="{{ filterset.form.category.name }}" id="category_id" class="form-control">
                        <option value="">Выберите категорию</option>
                        {% for cat in cat_list%}
                            <option value="{{cat.0}}"  {% if cat.0 == filterset.form.category.value %} selected {%endif%}>{{cat.1}}</option>
                        {%endfor%}
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" class="mt-3 btn-primary" value="Найти" style="width:400px; background: linear-gradient(245deg,#F00B51,#73005C); color: white; font-size: 20px" />
                </td>
            </tr>
        </table>
    </form>

<!--Список постов-->
    <hr>
    {% if Post_search %}
        <h4 align="left"><b>Результаты поиска:</b></h4>
        {% for post in Post_search %}
        <table width="800px" border="1px" cellspacing="10" cellpadding="10">
            <tr align="left" bgcolor="#E5E5E5"  style="border-bottom: 0.5px solid gray">
                <td valign="bottom" style="">
                    <a href="{% url 'post_view_from_search_page' post.id %}" style="text-decoration: none; font-size: 20px; color: #000000"><b>{{ post.title }}</b></a>
                </td>

                <td align="right" width="16%" style="font-size: 10px">
                    {{ post.date_creation|date:"d F Y H:i" }}
                </td>
            </tr>
            <tr bgcolor="#FFFFFF" style="border-bottom: 0.5px solid gray;">
                <td align="left" colspan="2">
                    {{ post.body|safe|truncatewords:5 }}
                    <a href="{{ post.id }}"> Читать --></a>
                </td>
            </tr>
            <tr align="left" bgcolor="#E5E5E5">
                <td colspan="2">Автор <b>{{ post.author }}</b> в категории <b>"{{post.category|readable_category }}"</b>.</td>
            </tr>
            <br>
        </table>
        {% endfor %}
    {% else %}
        <h2><b>К сожалению, по Вашему запросу ничего не найдено :(</b></h2>
    {% endif %}
<!--Пагинация-->
    <hr>
    <div style="background: linear-gradient(245deg,#F00B51,#73005C); ; border-radius:10px; text-align: center; color: white; margin: 25px; padding: 5px">
       {% if page_obj.has_previous %}
           <a href="?{% url_replace page=1 %}">1</a>
           {% if page_obj.previous_page_number != 1 %}
               ...
               <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
           {% endif %}
       {% endif %}

       {{ page_obj.number }}

       {% if page_obj.has_next %}
           <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
           {% if paginator.num_pages != page_obj.next_page_number %}
               ...
               <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
           {% endif %}
       {% endif %}
        <br>
            <h6 style="color: black">Всего страниц: {{page_obj.paginator.num_pages }} </h6>
    </div>
{% endblock content %}

billboard/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Все объявления
{% endblock title %}


{% block content %}
<h1 align="left" style="color: ##333333"><b>Все посты</b></h1>
<hr>

<!--Список постов-->
{% for post in posts %}
<table width="600px" border="2px" cellspacing="10" cellpadding="10">
    {% if post.author.username == 'admin' %}
        <tr align="left" style="background: linear-gradient(245deg,#00FFED,#0088BA)">
    {%else%}
        <tr align="left"   style="border-bottom: 0.5px solid gray; background: linear-gradient(245deg,#FFCF1B,#FF8818)">
    {%endif%}
        <td valign="bottom" style="margin-right: 50px">
            <a href="{{ post.id }}" style="text-decoration: none; font-size: 20px; color: #000000"><b>{{ post.title }}</b></a>
        </td>

        <td align="right" width="17%" style="font-size: 10px;">
            {{ post.date_creation|month_translation}} {{post.date_creation|date:"H:i" }}
        </td>
    </tr>

    <tr style="border-bottom: 0.5px solid gray; background: linear-gradient(45deg,#CCCCCC,#FFFFFF)">
        <td align="left" colspan="2" height="100px">
            {{ post.body|safe|truncatewords:50 }}
            <a href="{{ post.id }}">Читать --></a>
        </td>
    </tr>


    {% if post.author.username == 'admin' %}
    <tr align="left" style="background: linear-gradient(245deg,#00FFED,#0088BA)">
    {%else%}
    <tr align="left" style="background: linear-gradient(245deg,#FFA62E,#EA4D2C)">
        {%endif%}
        <td colspan="2">Автор <b>{% if post.author.username == 'admin' %}АДминистрация сайта{%else%}{{ post.author }}{%endif%}</b> в категории <b>"{{post.category|readable_category }}"</b>.</td>
    </tr>
    <br>
</table>
{% endfor %}

    <!--Пагинация-->
    <hr>
    <div style="background: linear-gradient(245deg,#F00B51,#73005C); ; border-radius:10px; text-align: center; color: white; margin: 25px; padding: 5px">
       {% if page_obj.has_previous %}
           <a href="?page=1">1</a>
           {% if page_obj.previous_page_number != 1 %}
               ...
               <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
           {% endif %}
       {% endif %}

       {{ page_obj.number }}

       {% if page_obj.has_next %}
           <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
           {% if paginator.num_pages != page_obj.next_page_number %}
               ...
               <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
           {% endif %}
       {% endif %}
        <br>
                <h6 style="color: black;">Всего страниц: {{page_obj.paginator.num_pages }} </h6>
    </div>
{% endblock content %}

billboard/templates/reply_on_comment.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Ответ на отклик
{% endblock title  %}


{% block content %}
    <h1 align="left" style="color: #333333"><b>Ответ на отклик к посту <em>"{{Reply.comment_post}}"</em></b></h1>
    <hr>
    <div align="left" style=" box-shadow: 0 0 10px 1px #330000; border-radius:20px; width: 800px; margin-left:20px; padding: 15px; background: linear-gradient(245deg,#B6C1D4,#92F1D5)">
        <figure>
          <blockquote class="blockquote">
            <p>{{ Reply.text }}</p>
          </blockquote>
          <figcaption class="blockquote-footer">
            Отклик от <cite title="Source Title">{{ Reply.author }}</cite>, {{ Reply.date_creation|month_translation }} {{Reply.date_creation|date:"H:i"}}
          </figcaption>
        </figure>
        <form method="post">
            {% csrf_token %}
            <input
                    id="response_text"
                    name="response_text"
                    class="form-control"
                    placeholder="Напечатайте Ваш ответ на отклик здесь...">

            <br>
            <input type="hidden" name="Reply_id" value="{{ Reply.id }}" />
            <button name="action" value="send_reply" style="text-align:right; font-size: 12px" class="btn btn-success">Отправить ответ</button>
        </form>
    </div>
{% endblock content %}

billboard/templates/sample.html
{% extends 'flatpages/default.html' %}


{% block title %}
Заголовок вкладки
{% endblock title  %}
<!-- Это заготовка для создания других тэмплейтов в этом приложении -->

{% block content %}
    <h1 align="left" style="color: #333333"><b>Заголовок здесь</b></h1>
    <hr>


    <div align="center" class="form-group" style="margin-bottom: 25px">
        Текст здесь
        <hr>
    </div>
{% endblock content %}